---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(smatr)
library(janitor)
library(skimr)
library(gridExtra)
```


```{r, warning=FALSE}
biomass_data <- read_csv(here("data/biomass_conversions.csv"), na = c('#DIV/0!', 'NA'))
```

## Clean variable names

```{r}
biomass_data <- biomass_data |> clean_names() 
``` 

## Clean taxa

```{r}
# Table of counts
biomass_data$taxa |> tabyl()

# Correct typo and checking
biomass_data |> 
  mutate(taxa_clean = case_when(taxa == "salinator" ~ "Salinator",
                          TRUE ~ taxa)) |> 
  select(taxa, taxa_clean) |> 
  filter(taxa == "salinator")

# Making changes
biomass_data_taxaclean <- biomass_data |> 
  mutate(taxa_clean = case_when(taxa == "salinator" ~ "Salinator",
                          TRUE ~ taxa)) |> 
  filter(!taxa == "") # Dropping empty taxa

biomass_data_taxaclean$taxa_clean |> tabyl()
``` 

## Create observation number

```{r}
biomass_wobs <- biomass_data_taxaclean |> 
  mutate(obs_num = row_number())
```

## Outliers

Obs: 5747, 3859

```{r}
# A Clevaland plot
ggplot(biomass_wobs, aes(x = dm_g, y = obs_num, label = obs_num)) +
  geom_point(colour = "white") +
  geom_text() + 
  theme_bw()         
```

### By species

Compute z scores for dm and wm for each species 
```{r}
# Compute SD and Mean
biomass_wobs_z |> 
  group_by(taxa_clean) |> 
  summarise(sp_n = n(),
            sp_mean_dm = mean(dm_g,na.rm = TRUE),
            sp_sd_dm = sd(dm_g, na.rm = TRUE))


```


### Z score method

Z scores = (dm - mean(dm))/sd(dm)

Make clevaland plot for each speices and plot where their 3SD is using geom_vline
```{r}
mean_dm <- mean(biomass_wobs_z$dm_g, na.rm = TRUE)
sd_dm <- sd(biomass_wobs_z$dm_g, na.rm = TRUE)


biomass_wobs_z <- biomass_wobs  |> 
  mutate(z_dm = scale(dm_g, center = TRUE, scale = TRUE),
         centered_dm = scale(dm_g, center = TRUE, scale = FALSE),
         manual_z_dm = (dm_g-mean_dm)/sd_dm,
         manual_centered_dm = (dm_g-mean_dm)
  )

# An illustration of scale()
biomass_wobs_z |> 
  select(ends_with("dm"), -starts_with("af"))

# A Clevaland plot
ggplot(biomass_wobs_z, aes(x = z_dm, y = obs_num, label = obs_num)) +
  geom_point(colour = "white") +
  geom_text() + 
  geom_vline(xintercept = sd_dm*3, colour = "yellow") 

summary(biomass_wobs_z$z_dm)
```

## Cooks Distance

Cook statistic in linear regression

```{r}

```

