---
title: "Regression Analysis"
author: "Josh Nitschke"
date: "2023-08-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install.packages("remotes")
remotes::install_github("traitecoevo/smatr")

library(tidyverse)
library(here)
library(smatr)
library(janitor)
library(skimr)
library(gridExtra)
library(olsrr)
library(purrr)
library(tidyr)
```

## read in processed data
```{r}
biomass_frozen_outliers_identified <- read_csv(here("data/processed/biomass_frozen_outliers_identified.csv"))
```

## running SMA's on untransformed data
```{r}
taxa_nested_sma <- biomass_frozen_outliers_identified |> 
  group_nest(taxa_clean) |>
  mutate(sma_object = map(.x = data,
                          ~ sma(dm_g ~ wm_g, data = .x)))

```

### Check assumptions

#### homogeneity of variance
```{r}
taxa_nested_sma_fitted_resid <- taxa_nested_sma |> 
  mutate(fitted_resid = map(.x = sma_object,
                             .f = ~ tibble(fitted = fitted(.x), residuals = residuals(.x))),
         fitted_resid_plot = map2(.x = fitted_resid,
                     .y = taxa_clean,
                     .f = ~ ggplot(data = .x, aes(x = fitted, y = residuals)) + 
                       ggtitle(.y) +
                       labs(x = "fitted value", y = "residual") +
                       geom_point() + 
                       geom_hline(yintercept = 0) +
                       theme_bw() + 
                       theme(panel.border = element_blank(), panel.grid.major = element_blank(), 
                       panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), 
                       axis.text = element_text(size = 12, colour = "black"), axis.title = element_text(size = 14))))
taxa_nested_sma_fitted_resid$fitted_resid_plot

```

#### Normality
```{r}
taxa_nested_sma_fitted_resid_qq <- taxa_nested_sma_fitted_resid |>
  mutate(qq = map2(.x = sma_object,
                  .y = taxa_clean,
                  .f = ~ plot(.x, which = "qq", main = paste("qq-plot:",.y))))
```
# Excluding outliers
## running SMA's on untransformed data
```{r}
taxa_nested_sma_outliers_removed <- biomass_frozen_outliers_identified |> 
  filter(keep_data == TRUE) |>
  group_nest(taxa_clean) |>
  mutate(sma_object = map(.x = data,
                          ~ sma(dm_g ~ wm_g, data = .x)))

```

### Check assumptions

#### homogeneity of variance
```{r}
taxa_nested_sma_outliers_removed_fitted_resid <- taxa_nested_sma_outliers_removed |> 
  mutate(fitted_resid = map(.x = sma_object,
                             .f = ~ tibble(fitted = fitted(.x), residuals = residuals(.x))),
         fitted_resid_plot = map2(.x = fitted_resid,
                     .y = taxa_clean,
                     .f = ~ ggplot(data = .x, aes(x = fitted, y = residuals)) + 
                       ggtitle(.y) +
                       labs(x = "fitted value", y = "residual") +
                       geom_point() + 
                       geom_hline(yintercept = 0) +
                       theme_bw() + 
                       theme(panel.border = element_blank(), panel.grid.major = element_blank(), 
                       panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), 
                       axis.text = element_text(size = 12, colour = "black"), axis.title = element_text(size = 14))))
taxa_nested_sma_outliers_removed_fitted_resid$fitted_resid_plot

```
Alternative method
```{r}
taxa_nested_sma_outliers_removed_fitted_resid2 <- taxa_nested_sma_outliers_removed |>
  mutate(scat = map2(.x = sma_object,
                  .y = taxa_clean,
                  .f = ~ plot(.x, which = "residual", main = .y)))
```

#### Normality
```{r}
taxa_nested_sma_outliers_removed_fitted_resid_qq <- taxa_nested_sma_outliers_removed_fitted_resid |>
  mutate(qq = map2(.x = sma_object,
                  .y = taxa_clean,
                  .f = ~ plot(.x, which = "qq", main = paste("qq-plot:",.y))))
```


## Running SMA's on log10-transformed data and plotting
```{r}
taxa_nested_sma_log10_plot <- biomass_frozen_outliers_identified |> 
  group_nest(taxa_clean) |>
  mutate(sma_log10_object = map(.x = data,
                          ~ sma(dm_g ~ wm_g, log = "xy", data = .x)),
         sma_log10_plots = map2(.x = sma_log10_object,
                         .y = taxa_clean,
                         .f = ~ plot(.x, xlab = "wet mass (g)", ylab = "dry mass (g)", main = .y)))
         
taxa_nested_sma_log10_plot$sma_log10_object
```

### Pull out regression equation for back transformation

```{r}
# Get coefficients from SMA

taxa_nested_sma_log10_plot_coef <- taxa_nested_sma_log10_plot |>
  mutate(coef = map(.x = sma_log10_object,
                    .f = ~smatr:::coef.sma(.x)),
         "95_conf_int" = map(.x = sma_log10_object,
                             .f = ~confint(.x, level = 0.95)))
taxa_nested_sma_log10_plot_coef$"95_conf_int"

taxa_unnested_sma_log10_plot_coef <- taxa_nested_sma_log10_plot_coef |>
  unnest(cols = c(data))


coefs_ <- taxa_unnested_sma_log10_plot_coef |>
  mutate(coef_as_df = lapply(coef, as.data.frame)) |>
  select(taxa_clean, coef_as_df, "95_conf_int") |>
  unique()
coefs_


coefs <- data.frame(taxon = taxa_nested_sma_log10_plot_coef$taxa_clean, 
                    coef_value = list_c(taxa_nested_sma_log10_plot_coef$coef), 
                    coefficient = names(list_c(taxa_nested_sma_log10_plot_coef$coef)),
                    conf_int_value = list_c(taxa_nested_sma_log10_plot_coef$"95_conf_int")) |> 
  pivot_wider(names_from = "coefficient", values_from = "coef_value")|>
  data.frame(elevation = c(coefs$elevation), slope = c(coefs$slope))

coefs





intercept <- smatr:::coef.sma(log10_dry_wet_sma)[1] # Take the first value
intercept

slope <- smatr:::coef.sma(log10_dry_wet_sma)[2] # Take the second value
slope

# log10(DM) = slope * log10(WM) + intercept
# Exponentiate log10 using 10^
# DM = WM^slope * 10^intercept
# Create a new variable BT = Back transformed 
data_BF <- data |> 
  mutate(BT_DM = (wm_g^slope) * (10^intercept))  

# Plot back transformed data
# Histograms
hist(data_BF$dm_g) # Raw data
hist(data_BF$BT_DM) # Back transformed

# Scatterplots
# Raw data
ggplot(data_BF, aes(x = dm_g, y= wm_g)) +
  geom_point(alpha = 0.50) 

# Back transformed
ggplot(data_BF, aes(x = BT_DM, y= wm_g)) +
  geom_point(alpha = 0.50)
```
