---
title: "smatr"
author: "Fonti"
date: "2023-07-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(smatr)
library(janitor)
library(skimr)
library(gridExtra)
```

```{r, warning=FALSE}
biomass_data <- read_csv(here("data/biomass_conversions.csv"), na = c('#DIV/0!', 'NA'))
```

### Precleaning

```{r}
biomass_frozen <- biomass_data %>%
  filter(`Preservation Method` == "Frozen") |> 
  clean_names() |> 
  data.frame()


### Overview
skim(biomass_frozen)
```


### Exploration plots

minimum mass cut-off

```{r}
#No cut-off
biomass_frozen_all <- ggplot(data = biomass_frozen, aes(x = dm_g, y= wm_g)) +
  geom_point() + 
  geom_line(stat="smooth", method =
"lm", lwd = 0.5) + 
  scale_x_log10() +
  scale_y_log10() 

# mass >= 0.001 g
biomass_frozen_mass_cutoff <- biomass_frozen |>
  filter(wm_g >=0.001, dm_g >=0.001) |>
  ggplot(aes(x = dm_g, y= wm_g)) +
  geom_point() + 
  geom_line(stat="smooth", method =
"lm", lwd = 0.5) + 
  scale_x_log10() +
  scale_y_log10() 

cutoff_compare <- grid.arrange(biomass_frozen_all, biomass_frozen_mass_cutoff, nrow = 1)
cutoff_compare
```

What are these groupings we see in the smatr plots??

```{r}
# By zone
ggplot(data = biomass_frozen, aes(x = dm_g, y= wm_g)) +
  geom_point() + 
  geom_line(aes(group = zone, colour = zone), stat="smooth", method =
"lm", lwd = 0.5) + 
  scale_x_log10() +
  scale_y_log10() 

# By site
ggplot(data = biomass_frozen, aes(x = dm_g, y= wm_g)) +
  geom_point() + 
  geom_line(aes(group = site, colour = site), stat="smooth", method =
"lm", lwd = 0.5) + 
  scale_x_log10() +
  scale_y_log10() 

biomass_frozen |> 
  filter(taxa == "Amphipoda") |> 
ggplot(aes(x = dm_g, y= wm_g)) +
  geom_point(alpha = 0.50) + stat_smooth(method = "lm")

# Linear or non-linear?
biomass_frozen |> 
  filter(taxa == "Amphipoda") |> 
ggplot(aes(x = dm_g, y= wm_g)) +
  geom_point(alpha = 0.50) + stat_smooth(method = "lm")
```

### Preanalysis

```{r}
data <- biomass_frozen |> 
  select(dm_g, wm_g) |> 
  mutate(log_dm_g = log10(dm_g + 0.5),
         log_wm_g = log10(wm_g + 0.5))
```

### Run a SMA

```{r}
dry_wet_sma <- sma(log_dm_g~wm_g, 
    log = "xy",
    data = data) 

plot(dry_wet_sma)

log10_dry_wet_sma <- sma(log_dm_g~log_wm_g, 
    data = data) 

log10_dry_wet_sma

plot(log10_dry_wet_sma)
```

### Pull out regression equation for back transformation

```{r}
# Get coefficients from SMA
smatr:::coef.sma(log10_dry_wet_sma)

intercept <- smatr:::coef.sma(log10_dry_wet_sma)[1] # Take the first value
intercept

slope <- smatr:::coef.sma(log10_dry_wet_sma)[2] # Take the second value
slope

# log10(DM) = slope * log10(WM) + intercept
# Exponentiate log10 using 10^
# DM = WM^slope * 10^intercept
# Create a new variable BT = Back transformed 
data_BF <- data |> 
  mutate(BT_DM = (wm_g^slope) * (10^intercept))  

# Plot back transformed data
# Histograms
hist(data_BF$dm_g) # Raw data
hist(data_BF$BT_DM) # Back transformed

# Scatterplots
# Raw data
ggplot(data_BF, aes(x = dm_g, y= wm_g)) +
  geom_point(alpha = 0.50) 

# Back transformed
ggplot(data_BF, aes(x = BT_DM, y= wm_g)) +
  geom_point(alpha = 0.50)
```


### Pulling out the residuals to calculate SF (smearing factor)

cf Mährlein et al 2016 pg 43

```{r}
# To get residuals of SMA
resid <- residuals(log10_dry_wet_sma)
resid 

# To get sample size
n <- length(resid)
n

# Calculate SF
SF <- 1/n * sum(10^resid) 
SF # Similar to values in paper

# Now correct our back transformed values with SF
data_BF_corrected <- data_BF |> 
  mutate(BT_DM_corrected = BT_DM*SF)

# Plot back transformed data
# Histograms
hist(data_BF$dm_g) # Raw data
hist(data_BF_corrected$BT_DM_corrected) # Back transformed

# Scatterplots
# Raw data
ggplot(data_BF, aes(x = dm_g, y= wm_g)) +
  geom_point(alpha = 0.50) 

# Back transformed
ggplot(data_BF_corrected, aes(x = BT_DM_corrected, y= wm_g)) +
  geom_point(alpha = 0.50)
```
















